
// 自定义可配置变量
// 用户可画最小宽度
var userDrawMinW = 30;
// 用户可画最小高度
var userDrawMinH = 20;
// 删除事件接口
function selectDivDeleteHandle(index) {
    alert('删除了第' + index + '个选择框')
}
window.onload=function(){var count=1;var delCount=null;var selfDiv=document.querySelector("#selectDiv");var topScrollDistance=document.body.scrollTop+document.documentElement.scrollTop;var leftScrollDistance=document.body.scrollLeft+document.documentElement.scrollLeft;if(selfDiv.parentNode){selfDiv.parentNode.addEventListener("scroll",function(){topScrollDistance=selfDiv.parentNode.scrollTop+document.body.scrollTop+document.documentElement.scrollTop;leftScrollDistance=selfDiv.parentNode.scrollLeft+document.body.scrollLeft+document.documentElement.scrollLeft})}document.addEventListener("scroll",function(){topScrollDistance=document.body.scrollTop+document.documentElement.scrollTop;leftScrollDistance=document.body.scrollLeft+document.documentElement.scrollLeft});selfDiv.onmousedown=function(e){var posx=e.offsetX;var posy=e.offsetY;var div=document.createElement("div");var node=document.createElement("div");node.className="tagDiv";var textnode=document.createTextNode(count+"");var node1=document.createElement("div");node1.className="delDiv";node1.onmousedown=function(en){en.stopPropagation();selfDiv.removeChild(div);delCount=parseInt(en.target.parentNode.querySelector(".tagDiv").innerHTML);var allTag=document.querySelectorAll(".tagDiv");for(var i=0;i<allTag.length;i++){var element=allTag[i];if(parseInt(element.innerHTML)>delCount){element.innerHTML=parseInt(element.innerHTML)-1}}count--;selectDivDeleteHandle(delCount)};div.className="selectDiv";div.onmousedown=function(ed){ed.stopPropagation()};div.style.left=e.offsetX+"px";div.style.top=e.offsetY+"px";selfDiv.appendChild(div);selfDiv.onmouseup=function(){if(parseInt(div.style.width)>userDrawMinW&&parseInt(div.style.height)>userDrawMinH){}else{selfDiv.removeChild(div)}selfDiv.onmousemove=null};selfDiv.onmousemove=function(ev){if(ev.clientX>(posx+selfDiv.offsetLeft-leftScrollDistance)){div.style.left=posx+"px";div.style.top=posy+"px"}else{div.removeAttribute("style");div.style.right=(parseInt(selfDiv.style.width)-posx)+"px";div.style.bottom=(parseInt(selfDiv.style.height)-posy)+"px"}div.style.width=Math.abs(ev.clientX-selfDiv.offsetLeft-(posx-leftScrollDistance))+"px";div.style.height=Math.abs(topScrollDistance-Math.abs(ev.clientY-selfDiv.offsetTop-posy))+"px";selfDiv.onmouseup=function(){if(parseInt(div.style.width)>userDrawMinW&&parseInt(div.style.height)>userDrawMinH){node.appendChild(textnode);div.appendChild(node);div.append(node1);count++}else{selfDiv.removeChild(div)}selfDiv.onmousemove=null;selfDiv.onmouseup=null}}}};